### ISSUE TITLE
Lua script fails with non-ASCII character

### ISSUE THREAD

**Issue by mehaase** [scrapinghub/splash#174]
According [to this](http://lua-users.org/wiki/LuaUnicode), I think Lua defaults to UTF-8 encoding for scripts. That link isn't extremely clear, but also the Lua REPL (Lua 5.2.3) handles string literals that contain UTF-8 characters, which further convinces me that Lua expects scripts to be encoded in UTF-8.

Splash (@de9374) raises a UnicodeDecodeError if the Lua script contains any non-ASCII characters, even if those characters appear in a comment. Here's a program that triggers the error:

    function main(splash)
        --你好
        return {ok='ok'}
    end

Traceback:

        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1439, in dataReceived
            finishCallback(data[contentLength:])
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1668, in _finishRequestBody
            self.allContentReceived()
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1731, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 827, in requestReceived
            self.process()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
            self.render(resrc)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
            body = resrc.render(self)
          File "splash/resources.py", line 36, in render
            return Resource.render(self, request)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "splash/resources.py", line 89, in render_POST
            return self.render_GET(request)
          File "splash/resources.py", line 61, in render_GET
            pool_d = self._getRender(request, render_options)
          File "splash/resources.py", line 190, in _getRender
            lua_source = options.get_lua_source(),
          File "splash/render_options.py", line 131, in get_lua_source
            return self.get("lua_source")
          File "splash/render_options.py", line 69, in get
            value = type(value)
        exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-28: ordinal not in range(128

I think it's safe to assume that Lua scripts are encoded with UTF-8 and handle them accordingly.

**Comment by kmike** [comment]
Interesting - there are tests for unicode handling (https://github.com/scrapinghub/splash/blob/de93746525e1f92e1bfe3112ed4915fc6dd54497/splash/tests/test_execute.py#L62), and they pass. But when you use the UI it fails.
