### ISSUE TITLE
Try to resolve the "No module named  slyd.tap error"?

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/splash#285]
When I start bin/slyd i received the following error in cent-os

slyd]$ bin/slyd
2015-08-27 17:18:29+0530 [-] Log opened.
2015-08-27 17:18:29.318689 [-] Splash version: 1.6
2015-08-27 17:18:29.319315 [-] Qt 4.8.5, PyQt 4.10.1, WebKit 537.21, sip 4.14.6, Twisted 15.2.1, Lua 5.1
2015-08-27 17:18:29.319412 [-] Open files limit: 1024
2015-08-27 17:18:29.319473 [-] Open files limit increased from 1024 to 4096
2015-08-27 17:18:29.534741 [-] Xvfb is started: ['Xvfb', ':2431', '-screen', '0', '1024x768x24']
Xlib:  extension "RANDR" missing on display ":2431".
2015-08-27 17:18:29.637987 [-] Traceback (most recent call last):
2015-08-27 17:18:29.638202 [-]   File "bin/slyd", line 41, in <module>
2015-08-27 17:18:29.638312 [-]     splash.server.main()
2015-08-27 17:18:29.638408 [-]   File "/usr/lib/python2.7/site-packages/splash/server.py", line 373, in main
2015-08-27 17:18:29.638572 [-]     max_timeout=opts.max_timeout
2015-08-27 17:18:29.638665 [-]   File "/usr/lib/python2.7/site-packages/splash/server.py", line 279, in default_splash_server
2015-08-27 17:18:29.638801 [-]     max_timeout=max_timeout
2015-08-27 17:18:29.638887 [-]   File "bin/slyd", line 15, in make_server
2015-08-27 17:18:29.638981 [-]     from slyd.tap import makeService     
2015-08-27 17:18:29.639099 [-] ImportError: No module named slyd.tap

How could it resolve

**Comment by kmike** [comment]
Splash doesn't use slyd in any way, it must be some Portia customization. Could you please raise an issue in Portia bug tracker (https://github.com/scrapinghub/portia)?
