### ISSUE TITLE
wrapped C/C++ object of type SplashCookieJar has been deleted

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#321]
I've got this exception when running qt5 tests in parallel ([here](https://travis-ci.org/scrapinghub/splash/jobs/85749652)):

```
2015-10-16 15:14:22.239706 [-] Traceback (most recent call last):

2015-10-16 15:14:22.239924 [-]   File "/home/travis/build/scrapinghub/splash/splash/network_manager.py", line 378, in createRequest

2015-10-16 15:14:22.240410 [-]     reply = super(SplashQNetworkAccessManager, self).createRequest(operation, request, outgoingData)

2015-10-16 15:14:22.240684 [-]   File "/home/travis/build/scrapinghub/splash/splash/network_manager.py", line 94, in createRequest

2015-10-16 15:14:22.240988 [-]     self._handle_request_cookies(request)

2015-10-16 15:14:22.241150 [-]   File "/home/travis/build/scrapinghub/splash/splash/network_manager.py", line 201, in _handle_request_cookies

2015-10-16 15:14:22.241515 [-]     cookiejar.update_cookie_header(request)

2015-10-16 15:14:22.241681 [-]   File "/home/travis/build/scrapinghub/splash/splash/cookies.py", line 16, in update_cookie_header

2015-10-16 15:14:22.241942 [-]     cookies = self.cookiesForUrl(request.url())

2015-10-16 15:14:22.242112 [-] RuntimeError: wrapped C/C++ object of type SplashCookieJar has been deleted
```

Not sure if it is caused by https://github.com/scrapinghub/splash/pull/316 or not.

**Comment by kmike** [comment]
For now this should be fixed by reverting #316.
