### ISSUE TITLE
request/response callbacks are called after processing is stopped

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#356]
I've got the following error in logs:

```
2015-12-22 18:39:50.524612 [-] "172.17.0.15" - - [22/Dec/2015:18:39:47 +0000] "POST /execute HTTP/1.1" 200 2189423 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1"
2015-12-22 18:39:50.811490 [render] [139666329081392] loadFinished: RenderErrorInfo(type='Network', code=301, text='Protocol "" is unknown', url='')
2015-12-22 18:39:50.826141 [-] "172.17.0.15" - - [22/Dec/2015:18:39:50 +0000] "GET / HTTP/1.0" 200 5434 "-" "-"
2015-12-22 18:39:53.486719 [network-manager] error in on_response callback
2015-12-22 18:39:53.487285 [network-manager] Traceback (most recent call last):
	  File "/app/splash/lua_runner.py", line 108, in dispatch
	    cmd = self.coro.send(self.lua.python2lua(args))  # cmd is a next async command
	  File "lupa/_lupa.pyx", line 833, in lupa._lupa._LuaThread.send (lupa/_lupa.c:13042)
	  File "lupa/_lupa.pyx", line 884, in lupa._lupa.resume_lua_thread (lupa/_lupa.c:13670)
	StopIteration
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/app/splash/network_manager.py", line 302, in _run_webpage_callbacks
	    cb(*args)
	  File "/app/splash/qtrender_lua.py", line 954, in _callback
	    req = _ExposedRequest.from_har(self.lua, exceptions, har_entry['request'])
	  File "/app/splash/qtrender_lua.py", line 1152, in from_har
	    info=har_request,
	  File "/app/splash/qtrender_lua.py", line 1133, in __init__
	    super(_ExposedRequest, self).__init__(lua, exceptions)
	  File "/app/splash/qtrender_lua.py", line 378, in __init__
	    self.commands = lua.python2lua(commands)
	AttributeError: 'NoneType' object has no attribute 'python2lua'
```

**Comment by pawelmhm** [comment]
Can it be because network_manager continues to download scheduled requests even after load finished event fires and response is returned to Splash user?

I noticed something like this happening very often, e.g. on walmart.com

```
2016-03-07 11:28:03.946779 [pool] [140244054651568] SLOT 23 done with <splash.qtrender.PngRender object at 0x7f8d5ef23ac8>
2016-03-07 11:28:03.947206 [events] {"load": [1.71, 1.45, 1.38], "_id": 140244054651568, "fds": 76, "client_ip": "127.0.0.1", "rendertime": 4.503134489059448, "maxrss": 316236, "method": "GET", "qsize": 0, "status_code": 200, "path": "/render.png", "args": {"uid": 140244054651568, "url": "http://walmart.com"}, "active": 0, "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36", "timestamp": 1457346483}
2016-03-07 11:28:03.947546 [-] "127.0.0.1" - - [07/Mar/2016:10:28:03 +0000] "GET /render.png?url=http://walmart.com HTTP/1.1" 200 481076 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
2016-03-07 11:28:03.947686 [pool] SLOT 23 is available
2016-03-07 11:28:03.954130 [network] [140244054651568] GET http://ll-us-i5.wal.co/dfw/4ff9c6c9-2b06/k2-_3b3526aa-4dd0-437a-9b9e-da548a4a006a.v1.jpg-0e372b1493e4ff4bd2526f00689bf4447bd458a3-optim-1364x300.jpg?odnWidth=1364&odnHeight=300
```

response is returned, splash logs message indicating it is all done, but one remaining request is still downloaded after all processing is done. If there would be some callback assigned to this I suppose this callback would be executed.

We could deal with this by keeping track of all replies downloaded by NAT and adding close() method to NAT, which would abort() all replies after response has already been returned to Splash user. close() could be called by browser_tab object just before deleteLater() in browser tab close() method.

**Comment by kmike** [comment]
@pawelmhm are you still getting this after https://github.com/scrapinghub/splash/pull/395 fix?

**Comment by pawelmhm** [comment]
yeah seems like so, I dont get any segfaults when this happens anymore so there is progress, but it seems like requests are still processed.

**Comment by pawelmhm** [comment]
so I digged deeper into this, see my [dev branch here](https://github.com/scrapinghub/splash/compare/master...pawelmhm:cancel_on_load?expand=1) but I didn't manage to fix this problem completely. Problem can be easily reproduced with resource like this [one here](https://github.com/scrapinghub/splash/compare/master...pawelmhm:cancel_on_load?expand=1#diff-3cb74b2bdc3baec8d0368069cdcab2fdR738) it is simple ajax call that is set with setTimeout() after page load. It turns out that this call is almost always scheduled with splash and logged in logs despite the fact that it fires long after processing is done and response returned to splash user. 

What puzzles me is that even if we call abort() on outstanding request after processing is done this still does not stop request from being fired. Splash will no longer log: "request headers downloaded", and "request finished", instead it will log "response aborted()", so callbacks will not be executed which sounds cool. But it's not fixing problem, just removing this from sight. If you browse test server logs you'll still see that test server is receiving request. This means that reply.abort() seems not to work on requests fired with ajax and setTimeout.

Easiest way to reproduce this is by checking out my branch, starting mockserver: 
```
> python splash/tests/mockserver.py
```

and then:
```
> curl http://localhost:8050/render.png?url=http://localhost:8998/requests-after-load
```
and watching splash logs, output on my branch looks like this:

```
2016-03-18 13:02:48.132363 [pool] [140304517033152] SLOT 0 done with <splash.qtrender.PngRender object at 0x7f9b30e68828>
2016-03-18 13:02:48.132836 [events] {"path": "/render.png", "method": "GET", "args": {"uid": 140304517033152, "url": "http://localhost:8998/requests-after-load"}, "load": [0.28, 0.26, 0.29], "_id": 140304517033152, "fds": 26, "status_code": 200, "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36", "qsize": 0, "active": 0, "rendertime": 0.0731201171875, "maxrss": 143092, "timestamp": 1458302568, "client_ip": "127.0.0.1"}
2016-03-18 13:02:48.132960 [-] "127.0.0.1" - - [18/Mar/2016:12:02:47 +0000] "GET /render.png?url=http://localhost:8998/requests-after-load HTTP/1.1" 200 18919 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
2016-03-18 13:02:48.133106 [pool] SLOT 0 is available
2016-03-18 13:02:48.133578 [network] [140304517033152] GET http://localhost:8998/requests-after-load/other_resource
2016-03-18 13:02:48.134136 [network-manager] timed out, aborting: http://localhost:8998/requests-after-load/other_resource
```

so it says: "aborting" and we're calling reply.abort(), nevertheless mockserver logs tell different story

```
2016-03-18 12:58:20+0100 [-] Log opened.
2016-03-18 12:58:20+0100 [-] Mock server running at http://0.0.0.0:8998 (http), https://0.0.0.0:8999 (https) and http://0.0.0.0:8990 (proxy) and http://0.0.0.0:8995 (proxy with auth, user: test)
^[[6;5~	2016-03-18 13:02:48+0100 [-] "127.0.0.1" - - [18/Mar/2016:12:02:47 +0000] "GET /requests-after-load HTTP/1.1" 200 669 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1"
2016-03-18 13:02:48+0100 [-] "127.0.0.1" - - [18/Mar/2016:12:02:47 +0000] "GET /requests-after-load/other_resource HTTP/1.1" 200 81 "http://localhost:8998/requests-after-load" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1"

```

you cans see other_resource request is received in test server :confused:

**Comment by kmike** [comment]
The original traceback was caused by a stupid bug: `[resp]` was passed as a return_result function. It is fixed by https://github.com/scrapinghub/splash/commit/577f839740e29b603f8a59744f6080604c2c47cd.
