### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by kesavkolla** [scrapinghub/splash#373]
Is it possible to run splash on ARM?  I want to put this splash on my Rasberry Pi.  Is it possible to build docker image for ARM?  Any known limitations?

**Comment by kmike** [comment]
I have no idea :) Please share your experience if you try it!

**Comment by sibiryakov** [comment]
@kesavkolla Qt5 webkit is possible to build on ARM, python too I guess. So, major requirements are fit. I would try running it from source with all dependencies installed or build by hand.

**Comment by mkjiang** [comment]
Anyone succeeded or has already built a dockerfile? I am about to have a go but just in case.

**Comment by rava-dosa** [comment]
@mkjiang  Yes if you need some help you may visit [issue 575](https://github.com/scrapinghub/splash/issues/575)

**Comment by Imparium** [comment]
When I try to execute the dock on a ARM this happens:

pi@raspberrypi:~ $ sudo docker run -p 8050:8050 scrapinghub/splash
standard_init_linux.go:190: exec user process caused "exec format

**Comment by gallofeliz** [comment]
Trying with FROM ubuntu 18.04 : 

> E: Package 'libpng12-dev' has no installation candidate

Tried with resin/rpi-raspbian, I had an error too :

> Traceback (most recent call last):
>   File "/usr/bin/add-apt-repository", line 167, in <module>
>     sp = SoftwareProperties(options=options)
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
>     self.reload_sourceslist()
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
>     self.distro.get_sources(self.sourceslist)
>   File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
>     (self.id, self.codename))
> aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie

Regards

**Comment by heilwood** [comment]
installed on arm archlinux. All packages was installed manually:

sudo pacman -S python-pyqt5
sudo pacman -S python-sip-pyqt5 pyqt5-common
sudo pacman -S qt5-webkit
sudo pacman -S xorg-server-xvfb
yaourt -S ttf-wqy-zenhei-ibx
sudo pip install splash
sudo pip install lupa

python -m splash.server --port 8050

**Comment by landowark** [comment]
@heilwood 

> installed on arm archlinux.

I've been trying to get this to work with a Dockerfile and I've gotten as far as:

```
FROM agners/archlinuxarm

RUN pacman -Sy 
RUN pacman -S python-pyqt5 python-pip base-devel python-sip-pyqt5 pyqt5-common qt5-webkit xorg-server-xvfb nss libxcursor libxtst --noconfirm
RUN python -m  pip install splash lupa pyqtwebengine
ENTRYPOINT python -m splash.server --port 8050
EXPOSE 8050

```
But I keep running into the error:

`ImportError: /usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz, version Qt_5`

From what I've read I think some versions of splash have problems with the newer versions of Qt5. What version of both were you running?
