### ISSUE TITLE
splash segfaults if you pass filters but dont pass "url" argument

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#397]
Really interesting bug, if you want to use filters but dont pass "url" and try to make call to go() splash will segfault, following Python script reproduces the problem

```python
base_url = "http://localhost:8050/execute"
post_url = base_url + "?filters=easylist"
lua_source = "function main(splash) return splash:go('http://splash.readthedocs.com') end"
res = requests.post(post_url, data=json.dumps({"lua_source": lua_source}), headers={"content-type": "application/json"})
print(res.json())
```

This ends with SIGSEGV (Address boundary error)

``` 
> python3 ./bin/splash -v 3 --filters-path=dev/filters/                                                                                                           
2016-02-29 16:01:10.502342 [pool] [140131975982720] SLOT 0 is starting
2016-02-29 16:01:10.502430 [render] [140131975982720] function main(splash) return splash:go('http://splash.readthedocs.com') end
2016-02-29 16:01:10.505161 [render] [140131975982720] [lua_runner] dispatch cmd_id=__START__, args=None
2016-02-29 16:01:10.505255 [render] [140131975982720] [lua_runner] arguments are for command __START__, waiting for result of __START__
2016-02-29 16:01:10.505335 [render] [140131975982720] [lua_runner] send None
2016-02-29 16:01:10.505496 [render] [140131975982720] [lua_runner] got AsyncBrowserCommand(id=None, name='go', kwargs={'http_method': 'GET', 'baseurl': None, 'errback': '<an errback>', 'headers': None, 'url': 'http://splash.readthedocs.com', 'callback': '<a callback>', 'body': None})
2016-02-29 16:01:10.505586 [render] [140131975982720] [lua_runner] instructions used: 62
2016-02-29 16:01:10.505673 [render] [140131975982720] [lua_runner] executing AsyncBrowserCommand(id=0, name='go', kwargs={'http_method': 'GET', 'baseurl': None, 'errback': '<an errback>', 'headers': None, 'url': 'http://splash.readthedocs.com', 'callback': '<a callback>', 'body': None})
2016-02-29 16:01:10.505749 [render] [140131975982720] HAR event: _onStarted
2016-02-29 16:01:10.505872 [render] [140131975982720] callback 0 is connected to loadFinished
2016-02-29 16:01:10.507348 [network] [140131975982720] GET http://splash.readthedocs.com/

fish: “python3 ./bin/splash -v 3 --fil…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by pawelmhm** [comment]
doing git bisect seems like this is really old bug, I went to version 1.6 and  turns out in this version it was also crashing, but with somewhat better error message

Traceback from version 1.6:

```
2016-02-29 16:10:14.346721 [-] Traceback (most recent call last):
2016-02-29 16:10:14.346817 [-]   File "/home/pawel/scrapinghub/splash/splash/network_manager.py", line 370, in createRequest
2016-02-29 16:10:14.346951 [-]     request = filter.process(request, render_options, operation, outgoingData)
2016-02-29 16:10:14.347023 [-]   File "/home/pawel/scrapinghub/splash/splash/request_middleware.py", line 94, in process
2016-02-29 16:10:14.347112 [-]     url, options = self._url_and_adblock_options(request, render_options)
2016-02-29 16:10:14.347185 [-]   File "/home/pawel/scrapinghub/splash/splash/request_middleware.py", line 109, in _url_and_adblock_options
2016-02-29 16:10:14.347280 [-]     domain = urlparse.urlsplit(render_options.get_url()).netloc
2016-02-29 16:10:14.347342 [-]   File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 97, in get_url
2016-02-29 16:10:14.347407 [-]     return self._get_url("url")
2016-02-29 16:10:14.347459 [-]   File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 88, in _get_url
2016-02-29 16:10:14.347523 [-]     url = self.get(name, default, type=None)
2016-02-29 16:10:14.347575 [-]   File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 80, in get
2016-02-29 16:10:14.347638 [-]     raise BadOption("Missing argument: %s" % name)
2016-02-29 16:10:14.347701 [-] splash.render_options.BadOption: Missing argument: url
fish: “python ./bin/splash -v 3 --filt…” terminated by signal SIGABRT (Abort)
```
