### ISSUE TITLE
After migrating to Python 3 we no longer see Tracebacks in splash logs in some cases

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#398]
When researching #397 I found out that python 3 no longer shows full tracebacks in logs. Compare logs for different Python versions:

Python 2

```
2016-02-29 16:23:16.446363 [network] [139649002961736] GET http://splash.readthedocs.com/
Traceback (most recent call last):
  File "/home/pawel/scrapinghub/splash/splash/network_manager.py", line 382, in createRequest
    request = middleware.process(request, render_options, operation, outgoingData)
  File "/home/pawel/scrapinghub/splash/splash/request_middleware.py", line 110, in process
    url, options = self._url_and_adblock_options(request, render_options)
  File "/home/pawel/scrapinghub/splash/splash/request_middleware.py", line 125, in _url_and_adblock_options
    domain = urlsplit(render_options.get_url()).netloc
  File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 100, in get_url
    return self._get_url("url")
  File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 91, in _get_url
    url = self.get(name, default, type=None)
  File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 83, in get
    type='argument_required')
  File "/home/pawel/scrapinghub/splash/splash/render_options.py", line 32, in raise_error
    raise BadOption(params)
splash.exceptions.BadOption: {'type': 'argument_required', 'argument': 'url', 'description': 'Required argument is missing: url'}
fish: “python ./bin/splash -v 3 --filt…” terminated by signal SIGABRT (Abort)
```

Python 3

```
2016-02-29 16:23:32.587872 [network] [140144381286104] GET http://splash.readthedocs.com/
fish: “python3 ./bin/splash -v 3 --fil…” terminated by signal SIGSEGV (Address boundary error)                                                                        
```

Notice missing traceback in Python 3. This is pretty bad and it makes development difficult, you need to spend much more time trying to figure out where exactly exception occured and what type of exception is it. 

Would be good to have exhaustive stacktraces back in Python 3.

**Comment by kmike** [comment]
I think in Python 3 we can use https://docs.python.org/3.4/library/faulthandler.html; when process segfaults all bets are off; Python 2 exception may be better only by chance.

**Comment by pawelmhm** [comment]
#402 fixes problem by printing tracebacks for unhandled errors in NAT middleware. faulthandler gives some tracebacks but they dont contain that much useful information. sys.excepthooks add some information sometimes, but they can duplicate info with normal tracebacks in some cases.
