### ISSUE TITLE
splash-jupyter is broken

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#407]
Now it fails for me with this exception:

```
Shutdown this notebook server (y/[n])? Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kmike/svn/splash/splash/kernel/__main__.py", line 19, in <module>
    start()
  File "/Users/kmike/svn/splash/splash/kernel/kernel.py", line 285, in start
    server.main(jupyter=True, argv=splash_args, server_factory=server_factory)
  File "/Users/kmike/svn/splash/splash/server.py", line 339, in main
    install_qtreactor(opts.verbosity >= 5)
  File "/Users/kmike/svn/splash/splash/server.py", line 18, in install_qtreactor
    qt5reactor.install()
  File "/Users/kmike/envs/py3-splash/lib/python3.4/site-packages/qt5reactor.py", line 412, in posixinstall
    installReactor(p)
  File "/Users/kmike/envs/py3-splash/lib/python3.4/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

Tests are also failing in master. I wonder if we should finally pin all ipython dependencies to known working versions.

**Comment by kmike** [comment]
Ouch, I've got this error with a modified splash.kernel.kernel file which imports twisted.reactor. It is not a problem in Splash master.
