### ISSUE TITLE
Is it a bug or my mistake?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#420]
this problem can reproduce on use python file call this script.
In Splash-Jupyter no problem.
In Http-UI has this problem.

```
function main(splash)
   splash:on_request(function(request)
      string.match("abcdef123", "%d+")
   end)
   splash:go('http://www.example.com')
end
```

In splash.server log, there is an error:

```
2016-03-18 17:05:12.775632 [network-manager] error in on_request callback
2016-03-18 17:05:12.776928 [network-manager] Traceback (most recent call last):
          File "/home/xiaoming/.pyenv/versions/py3-splash/lib/python3.4/site-packages/splash/network_manager.py", line 329, in _run_webpage_callbacks
            cb(*args)
          File "/home/xiaoming/.pyenv/versions/py3-splash/lib/python3.4/site-packages/splash/qtrender_lua.py", line 945, in _callback
            callback(req)
          File "lupa/_lupa.pyx", line 516, in lupa._lupa._LuaObject.__call__ (lupa/_lupa.c:8185)
          File "lupa/_lupa.pyx", line 1263, in lupa._lupa.call_lua (lupa/_lupa.c:18511)
          File "lupa/_lupa.pyx", line 1272, in lupa._lupa.execute_lua_call (lupa/_lupa.c:18624)
          File "lupa/_lupa.pyx", line 1225, in lupa._lupa.raise_lua_error (lupa/_lupa.c:17930)
        lupa._lupa.LuaError: [string "..."]:4: attempt to call field 'match' (a nil value)

```

**Comment by Youwotma** [comment]
Hi @genius001 

`string.match` is disabled in the sandbox https://github.com/scrapinghub/splash/blob/480c74bf4a0cb7bc484c986303ebec529f19dea4/splash/lua_modules/sandbox.lua#L19

Not sure why since `string.find` is allowed...

**Comment by kmike** [comment]
@Youwotma hm, string.find also has pathological cases which can't be caught by a sandbox, maybe we should disable it as well

**Comment by genius001** [comment]
Thanks.  @Youwotma @kmike
