### ISSUE TITLE
trying to return response.body from on_response raises 500 error

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#431]
Splash-Lua [response](http://splash.readthedocs.org/en/stable/scripting-response-object.html#splash-response-body) object has body attribute which is defined as binary capsule. If you try to return this object from within Lua it raises 500 internal server error.

To reproduce

``` Lua
treat = require("treat")

function main(splash)
    local bodies = {}
    splash:on_response(function (response) 
        bodies[0] = response.body
    end)

    splash:go(splash.args.url)
    return bodies
end
```

``` python
from urllib import urlencode, quote
import requests

with open("test.lua") as f:
    lua_source = f.read()

base_url = "http://localhost:8050/execute"
params = {
    "lua_source": lua_source,
    "filters": "easylist",
    "url": "http://httpbin.org/html"
}
f = requests.get(base_url + "?" + urlencode(params))
f.raise_for_status()
print(f.url + "\n\n" + f.text)
```

Splash logs in Python 2

```
2016-03-27 22:02:30.283935 [render] [140642491812392] cancelling 0 remaining timers
2016-03-27 22:02:30.283985 [pool] [140642491812392] SLOT 8 done with <splash.qtrender_lua.LuaRender object at 0x7fe9893c1890>
2016-03-27 22:02:30.284135 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
        self._runCallbacks()
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
        self._startRunCallbacks(result)
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/pawel/scrapinghub/splash/splash/resources.py", line 156, in _write_output
        return self._write_output(data, request, content_type)
      File "/home/pawel/scrapinghub/splash/splash/resources.py", line 147, in _write_output
        data = json.dumps(data, cls=SplashJSONEncoder)
      File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/home/pawel/scrapinghub/splash/splash/utils.py", line 40, in default
        return o.as_b64()
      File "/home/pawel/scrapinghub/splash/splash/utils.py", line 30, in as_b64
        return base64.b64encode(self.data).decode('utf-8')
      File "/usr/lib/python2.7/base64.py", line 53, in b64encode
        encoded = binascii.b2a_base64(s)[:-1]
    exceptions.TypeError: must be string or buffer, not None


```

Splash logs in Python 3 are different but also raise 500

```
016-03-27 22:05:35.592508 [pool] [140519703088208] SLOT 0 done with <splash.qtrender_lua.LuaRender object at 0x7fcd4b235710>
2016-03-27 22:05:35.592875 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/pawel/scrapinghub/splash/splash/qtrender_lua.py", line 548, in success
        cmd.return_result(True)
      File "/home/pawel/scrapinghub/splash/splash/lua_runner.py", line 34, in return_result
        self.dispatcher.dispatch(self.id, *args)
      File "/home/pawel/scrapinghub/splash/splash/qtrender.py", line 17, in stop_on_error_wrapper
        return meth(self, *args, **kwargs)
      File "/home/pawel/scrapinghub/splash/splash/qtrender_lua.py", line 1387, in dispatch
        super(SplashCoroutineRunner, self).dispatch(cmd_id, *args)
    --- <exception caught here> ---
      File "/home/pawel/scrapinghub/splash/splash/lua_runner.py", line 108, in dispatch
        cmd = self.coro.send(self.lua.python2lua(args))  # cmd is a next async command
      File "lupa/_lupa.pyx", line 833, in lupa._lupa._LuaThread.send (lupa/_lupa.c:13042)

      File "lupa/_lupa.pyx", line 884, in lupa._lupa.resume_lua_thread (lupa/_lupa.c:13670)

    builtins.StopIteration: 

2016-03-27 22:05:35.594159 [events] {"maxrss": 137640, "timestamp": 1459109135, "args": {"url": "http://httpbin.org/html", "lua_source": "treat = require(\"treat\")\n\nfunction main(splash)\n    local bodies = {}\n    splash:on_response(function (response) \n        bodies[0] = response.body\n    end)\n\n    splash:go(splash.args.url)\n    return bodies\nend\n", "filters": "easylist", "uid": 140519703088208}, "rendertime": 0.38851046562194824, "fds": 26, "error": {"type": "InternalError", "error": 500, "info": "a bytes-like object is required, not 'NoneType'", "description": "Unhandled internal error"}, "method": "GET", "_id": 140519703088208, "path": "/execute", "status_code": 500, "load": [0.53, 0.29, 0.18], "qsize": 0, "client_ip": "127.0.0.1", "active": 0, "user-agent": "python-requests/2.8.1"}
2016-03-27 22:05:35.594300 [-] "127.0.0.1" - - [27/Mar/2016:20:05:35 +0000] "GET /execute?lua_source=treat+%3D+require%28%22treat%22%29%0A%0Afunction+main%28splash%29%0A++++local+bodies+%3D+%7B%7D%0A++++splash%3Aon_response%28function+%28response%29+%0A++++++++bodies%5B0%5D+%3D+response.body%0A++++end%29%0A%0A++++splash%3Ago%28splash.args.url%29%0A++++return+bodies%0Aend%0A&url=http%3A%2F%2Fhttpbin.org%2Fhtml&filters=easylist HTTP/1.1" 500 141 "-" "python-requests/2.8.1"
2016-03-27 22:05:35.594447 [pool] SLOT 0 is available
2016-03-27 22:02:30.283935 [render] [140642491812392] cancelling 0 remaining timers
2016-03-27 22:02:30.283985 [pool] [140642491812392] SLOT 8 done with <splash.qtrender_lua.LuaRender object at 0x7fe9893c1890>
2016-03-27 22:02:30.284135 [-] Unhandled Error
    Traceback (most recent call last):
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
        self._runCallbacks()
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
        self._startRunCallbacks(result)
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/pawel/scrapinghub/splash/splash/resources.py", line 156, in _write_output
        return self._write_output(data, request, content_type)
      File "/home/pawel/scrapinghub/splash/splash/resources.py", line 147, in _write_output
        data = json.dumps(data, cls=SplashJSONEncoder)
      File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/home/pawel/scrapinghub/splash/splash/utils.py", line 40, in default
        return o.as_b64()
      File "/home/pawel/scrapinghub/splash/splash/utils.py", line 30, in as_b64
        return base64.b64encode(self.data).decode('utf-8')
      File "/usr/lib/python2.7/base64.py", line 53, in b64encode
        encoded = binascii.b2a_base64(s)[:-1]
    exceptions.TypeError: must be string or buffer, not None
```

I see we have warning in docs saying

> Currently you can’t access response.body in a splash:on_response callback.

So I see two potential issues here:
- if there is really no way to access response.body there, raise 400 and not 500
- perhaps there is some way to access body in callback? if yes that would be useful
#429

**Comment by kmike** [comment]
Accessing response.body is hard in qt; see https://github.com/scrapinghub/splash/issues/248 and https://github.com/scrapinghub/splash/issues/337. It'd be nice to implement this, but it is not straightforward.

Unhandled Error looks incorrect, it is a bug; it shouldn't raise an error. I think nil should be returned instead, to be consistent with other unavailable attributes.

**Comment by pawelmhm** [comment]
> Accessing response.body is hard in qt; see #248 and #337. It'd be nice to implement this, but it is not straightforward.

ah yes I see it is also on TODO list here #230 

> Unhandled Error looks incorrect, it is a bug; it shouldn't raise an error. I think nil should be returned instead, to be consistent with other unavailable attributes.

there seems to be general problem with errors in callbacks, we currently ignore them (there is ticket for on_request #208 but I think we ignore exceptions in on_response too?) and I think ATM we dont have any convenient way to propagate errors occurring in callbacks in NAT when processing response & request.

So probably fixing this 500 could require general cleanup of exceptions in response/request callbacks?

**Comment by kmike** [comment]
I think to fix error 500 is is enough to make response.body return nil when it is not available. This way it'd be consistent with how do other non-existing attributes work.

One way to fix error handling is to propogate errors from callbacks to the main script. But there is another way to handle errors in callbacks: https://github.com/scrapinghub/splash/issues/331. `splash:call_later` error handling already works this way - see http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-call-later and `timer:reraise()`.

**Comment by genius001** [comment]
Very expect add features:  Accessing response.body

Most of the case I have to access response.body.
It will be very convenient if has this feature.

**Comment by shaylevi2** [comment]
Anything new about accessing response.body?
Is there anyway to do it?
Anywhere I can look so I can add it myself?

**Comment by kmike** [comment]
@shaylevi2 there is some discussion at https://github.com/scrapinghub/splash/issues/248 and https://github.com/scrapinghub/splash/issues/337

**Comment by kmike** [comment]
I'm closing it as there is now a way to get response body from on_response callback.

**Comment by JavierRuano** [comment]
I have a question, is it possible retrieve body with qtrender_lua._ExposedElement or splash.qtrender_lua.command ?

And the difference with qtrender_lua._ExposedResponse
Response object exposed to Lua. This Response type doesn’t provide methods to manipulate a response.

I see qtrender_lua._ExposedResponse
qtrender_lua._ExposedResponse
** Response object exposed to Lua. This Response type doesn’t provide methods to manupulate a response.** 
Could it be changed? 
Perhaps a interface or what? 
Is the final state a lua result? (html, har, png ...) but splash conservate the state of render.

Is the previous text explained here?

Python -> Lua
Data is converted from Python to Lua in two cases:

method of an exposed Python object returns a result (most common example is a method of splash Lua object);
Python code calls Lua function with arguments - it could be e.g. an on_request callback.

https://splash.readthedocs.io/en/stable/internals/js-python-lua.html

**Comment by JavierRuano** [comment]
I have a question, is it possible retrieve body with qtrender_lua._ExposedElement or splash.qtrender_lua.command ?

And the difference with qtrender_lua._ExposedResponse
Response object exposed to Lua. This Response type doesn’t provide methods to manipulate a response.

I see qtrender_lua._ExposedResponse
qtrender_lua._ExposedResponse
** Response object exposed to Lua. This Response type doesn’t provide methods to manupulate a response.** 
Could it be changed? 
Perhaps a interface or what? 
Is the final state a lua result? (html, har, png ...) but splash conservate the state of render.

Is the previous text explained here?

Python -> Lua
Data is converted from Python to Lua in two cases:

method of an exposed Python object returns a result (most common example is a method of splash Lua object);
Python code calls Lua function with arguments - it could be e.g. an on_request callback.

https://splash.readthedocs.io/en/stable/internals/js-python-lua.html
