### ISSUE TITLE
ImportError: /opt/qt55/lib/libQt5Sql.so.5: undefined symbol: 

### ISSUE THREAD

**Issue by fengyingbanbo** [scrapinghub/splash#545]
root@ConvertImg:/usr/local/soft/splash-master# python3 -m splash.server --port=5000
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/soft/splash-master/splash/server.py", line 12, in <module>
    from splash.qtutils import init_qt_app
  File "/usr/local/soft/splash-master/splash/qtutils.py", line 17, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: /opt/qt55/lib/libQt5Sql.so.5: undefined symbol: _ZNK19QAbstractTableModel7siblingEiiRK11QModelIndex

**Comment by fengyingbanbo** [comment]
Anybody can tell me how to do with it?

**Comment by Gallaecio** [comment]
Did you manage to solve your issue?
