### ISSUE TITLE
Splash Page fetching time increasing  exponentially

### ISSUE THREAD

**Issue by Mideen** [scrapinghub/splash#795]
In my trial, I hit splash instance with 50 parallel threads. Each thread will get the page source of the URL. My splash instance default slots value is  50. Here, website fetching time increases exponentially with the number of parallel threads. I can get the perfect HTML source for 50 URLs. But the time increases from 2 seconds to 45 seconds from 1st URL to 50th URL respectively. Please help me to reduce the time for fetching the page source. 

My sample java code is 
`
public class SplashThread implements Runnable {

    private static final String splash ="http://localhost:8050/execute";

    private String script = URLEncoder.encode("function main(splash, args)  \n" +
            "splash:go(args.url)\n"+
            "  splash.images_enabled = false\n" +
            "  splash:on_request(function(request)\n" +
            "    if string.find(request.url, \".css\")~= nil then\n" +
            "        request.abort()\n" +
            "    end\n" +
            "end)\n" +
            "local html = splash:html()\n" +
            "return  html\n"+
            "end","UTF-8");

    private String url =null;

    public SplashThread(String url) throws UnsupportedEncodingException {
        this.url = url;

    }
    @Override
    public void run() {
        HttpClientUtil clientUtil =null;
        JSONObject json =null;
        try {
            Properties queryParms = new Properties();
            queryParms.put("url",url);
            queryParms.put("timeout","85.0");
            queryParms.put("lua_source",script);

            clientUtil = new HttpClientUtil(-1,false);
            HttpResponse response = clientUtil.doGet(splash,queryParms,null);
            String resp = ScrapyUtil.getResponseString(response,"UTF-8");
            

        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println("JSN}ON :: "+json);
        }
        finally {
            if(clientUtil!=null){
                try {
                    clientUtil.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

        }

    }
}`

I am scheduling 50 threads of  this runnable object with ScheduledExecutorService.

If I am fecthing the page source once by one, It will working perfectly. But I need to fecth concurrently.

**Comment by lopuhin** [comment]
Is splash process using 100% of one CPU core? Splash does support concurrent requests, but it's still using one core, so if one page takes say 1 second of CPU time, then it can not render 50 pages faster than in 50 seconds of CPU time. If you would like to use more cores with splash, one solution is https://github.com/TeamHG-Memex/aquarium

**Comment by Mideen** [comment]
Thanks for your replay @lopuhin. Is there any way to set to use more than one core with splash?. 

I tried with Aquarium, While installation when I use "docker-compose up" to start the Splash, It throws the following exception.

> Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 121, in get_project
    host=host, environment=environment
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 92, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docker_client.py", line 127, in docker_client
    client = APIClient(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 113, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'

Details 
Machine : Linux (ubuntu 14.04)
Python 2.7.6
Docker version 18.06.0-ce, build 0ffa825
docker-compose version 1.22.0, build f46880f

Please help us to solve this issue.

**Comment by lopuhin** [comment]
Discussing docker-compose issue in https://github.com/TeamHG-Memex/aquarium/issues/16, closing this one (feel free to reopen / comment)

**Comment by Mideen** [comment]
Sorry for this silly question.

Assume, I have 16 core CPU(s) machine. If I use Aquarium with four splash instance. At a time 4 out of 16 core will be used, other CPU cores would be idle?

Please correct me if I wrong.

**Comment by Mideen** [comment]
Is there any way to set to use more than one core for one splash instance? @lopuhin

**Comment by lopuhin** [comment]
> Assume, I have 16 core CPU(s) machine. If I use Aquarium with four splash instance. At a time 4 out of 16 core will be used, other CPU cores would be idle?

Yes, under full load usually no more than 400% of CPU will be used (if 100% is one core), although in practice it can even be a little higher than that. The load itself might span more cores unless you limit it to specific cores.

> Is there any way to set to use more than one core for one splash instance?

AFAIK no, at the moment it's impossible and I don't think there are any plans to support that. Using tools such as https://github.com/TeamHG-Memex/aquarium is preferable not only due to ability to use multiple cores, but also because splash might crash or become unresponsive on some websites, and having a pool of workers allows to mitigate this.

**Comment by Mideen** [comment]
> feel free to reopen / comment
Can't reopen this issue.

**Comment by lopuhin** [comment]
@Mideen can you check the load of the splash processes, how much CPU they are using? If the load is much less than 100% and the speed is still the same, then most likely this is an issue in the client code (Java code which makes HTTP requests to splash), because splash is regularly used in this fashion, and speed increases linearly when you add more cores. Unfortunately, I don't know Java well enough to give any advice - the code looks reasonable to me.

**Comment by lopuhin** [comment]
https://github.com/TeamHG-Memex/aquarium/issues/17 has more details, but let's continue here?

**Comment by Mideen** [comment]
Happy day ..!

I checked my CPU load. It reaches 400% (I have 4 core). 

Am I need to increase my CPU core(s)?

Even If I increased CPU core(s), the same exponential time increasing issue will occur if the more parallel threads hit at a time. Am I correct?

We are trying to use Splash for crawling purpose. At the time more than 100 parallel threads might be hit the Splash instance. So only we test the Splash with 100 automated parallel threads. Our main agenda is to reduce the website page fetch time as much as possible for crawling.

Can you please suggest anything to reduce this exponential time increase when I test with parallel threads.  

I tried Splash independent server and Splash with Aquarium. Both have the same exponential time increasing.

@lopuhin

**Comment by lopuhin** [comment]
> I checked my CPU load. It reaches 400% (I have 4 core).

This means that Splash cluster is under full load, and if you make more concurrent requests you won't get a speedup, but will only get higher latencies, which is I think what you are observing. In more details, I mean that you are limited by splash throughput (see e.g. here for an explanation of throughput and latency https://nirajrules.wordpress.com/2009/09/17/measuring-performance-response-vs-latency-vs-throughput-vs-load-vs-scalability-vs-stress-vs-robustness/)

I don't know the larger context of your system, but if I just had a list of URLs to download via splash, and assuming I'm not limited by the speed of the server that is serving this URLs (e.g. if these URLs are from multiple domain), then the total throughput is determined by the number of cores (assuming you add enough splash processes to saturate them), and I would try to aim at the number of concurrent requests that just puts the system under full load, and not make it much higher - in this case the latencies will be also reasonable.

From my experience, when rendering some random URLs, I could use 32-64 concurrent requests for an 8 core splash cluster.
