### ISSUE TITLE
Service broken when handing user rendering request.

### ISSUE THREAD

**Issue by starrify** [scrapinghub/splash#895]
I somehow managed to break the Splash service (halting the Docker container) when handling one `/execute` request. This is assumed to be an issue as the service is expected to live long whatever the user render request is.

Logs:
```
$ sudo docker run --rm -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash:3.3.1 --max-timeout 600
2019-04-04 00:36:19+0000 [-] Log opened.
2019-04-04 00:36:19.553676 [-] Splash version: 3.3.1
2019-04-04 00:36:19.554505 [-] Qt 5.9.1, PyQt 5.9.2, WebKit 602.1, sip 4.19.4, Twisted 18.9.0, Lua 5.2
2019-04-04 00:36:19.554586 [-] Python 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
2019-04-04 00:36:19.554733 [-] Open files limit: 1048576
2019-04-04 00:36:19.554818 [-] Can't bump open files limit
2019-04-04 00:36:19.658391 [-] Xvfb is started: ['Xvfb', ':746620526', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
2019-04-04 00:36:19.788923 [-] proxy profiles support is enabled, proxy profiles path: /etc/splash/proxy-profiles
2019-04-04 00:36:19.789097 [-] memory cache: enabled, private mode: enabled, js cross-domain access: disabled
2019-04-04 00:36:19.935316 [-] verbosity=1, slots=20, argument_cache_max_entries=500, max-timeout=600.0
2019-04-04 00:36:19.936514 [-] Web UI: enabled, Lua: enabled (sandbox: enabled)
2019-04-04 00:36:19.936977 [-] Site starting on 8050
2019-04-04 00:36:19.937077 [-] Starting factory <twisted.web.server.Site object at 0x7f6167626cf8>
2019-04-04 00:36:19.937341 [-] Server listening on http://0.0.0.0:8050
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
process 1: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
Traceback (most recent call last):
  File "/app/splash/lua_runner.py", line 138, in dispatch
    cmd = self.coro.send(as_lua)  # cmd is a next async command
  File "lupa/_lupa.pyx", line 833, in lupa._lupa._LuaThread.send (lupa/_lupa.c:13151)
  File "lupa/_lupa.pyx", line 884, in lupa._lupa.resume_lua_thread (lupa/_lupa.c:13770)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/splash/lua_runner.py", line 154, in dispatch
    res = self.lua.lua2python(self.result)
  File "/app/splash/lua_runtime.py", line 76, in lua2python
    return lua2python(self._lua, *args, **kwargs)
  File "/app/splash/lua.py", line 195, in lua2python
    return l2p(obj, depth=max_depth)
  File "/app/splash/lua.py", line 157, in l2p
    return tuple([l2p(el, depth-1) for el in obj])
  File "/app/splash/lua.py", line 157, in <listcomp>
    return tuple([l2p(el, depth-1) for el in obj])
  File "/app/splash/lua.py", line 182, in l2p
    for key, value in obj.items()
  File "/app/splash/lua.py", line 182, in <dictcomp>
    for key, value in obj.items()
  File "/app/splash/lua.py", line 187, in l2p
    "Lua %s objects are not allowed." % lupa.lua_type(obj)
ValueError: Lua function objects are not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/splash/qtrender.py", line 15, in stop_on_error_wrapper
    return meth(self, *args, **kwargs)
  File "/app/splash/qtrender_lua.py", line 2326, in dispatch
    super(SplashCoroutineRunner, self).dispatch(cmd_id, *args)
  File "/app/splash/lua_runner.py", line 160, in dispatch
    e.args[0]
splash.exceptions.ScriptError: {'message': "'main' returned bad result. Lua function objects are not allowed.", 'type': 'BAD_MAIN_ERROR'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/splash/browser_tab.py", line 592, in _on_wait_timeout
    callback()
  File "/app/splash/qtrender_lua.py", line 563, in success
    cmd.return_result(True)
  File "/app/splash/lua_runner.py", line 27, in return_result
    self.dispatcher.dispatch(self.id, PyResult.return_(*args))
  File "/app/splash/qtrender.py", line 17, in stop_on_error_wrapper
    self.return_error(e)
  File "/app/splash/qtrender_lua.py", line 632, in coro_error
    info = str(ex.args[0]["error"])
KeyError: 'error'
```

Sorry but there's no sample source code to attach for now: I haven't yet created a [MCVE](https://stackoverflow.com/help/mcve), while the full files that I'm working with:
- May not be shared publicly.
- Are somehow too big.
- Do not trigger this error every time.

I'll try to create a better sample renderer script and share it later.

**Comment by starrify** [comment]
**1.**
It's located that the earlier reported error happened upon a `return` line within `splash:with_timeout`.

**2.**
I tried to build some sample requests by mimicking the behavior, but I'm yet unable to reproduce the same issue that breaks the Docker container.

**3.**
One sample renderer is observed to trigger a similar error but would _not_ break the service.

Sample request and response:
```
$ curl 'http://localhost:8050/execute' -H "content-type: application/json" --data-binary $'{"lua_source":"function main(splash, args)\\r\\n  splash:go(\'http://httpbin.org\')\\r\\n  local ok, foo = splash:with_timeout(function ()\\r\\n    return true, splash:select(\'div\')\\r\\n  end, 10)\\r\\n  return {\\r\\n    foo = foo,\\r\\n    html = splash:html(),\\r\\n    png = splash:png(),\\r\\n    har = splash:har(),\\r\\n  }\\r\\nend"}' --compressed
{"description": "Unhandled internal error", "info": "'error'", "error": 500, "type": "InternalError"}
```

Sample renderer:
```lua
function main(splash, args)
  splash:go('http://httpbin.org')
  local ok, foo = splash:with_timeout(function ()
    return true, splash:select('div')
  end, 10)
  return {
    foo = foo,
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

Sample log:
```
$ sudo docker run --rm -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash:3.3.1 --max-timeout 600
(MULTIPLE LINES OMITTED)
2019-04-04 01:36:54.272357 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/app/splash/browser_tab.py", line 54, in wrapped
	    return meth(self, *args, **kwargs)
	  File "/app/splash/browser_tab.py", line 547, in _on_content_ready
	    callback()
	  File "/app/splash/qtrender_lua.py", line 707, in success
	    cmd.return_result(True)
	  File "/app/splash/lua_runner.py", line 27, in return_result
	    self.dispatcher.dispatch(self.id, PyResult.return_(*args))
	--- <exception caught here> ---
	  File "/app/splash/qtrender.py", line 15, in stop_on_error_wrapper
	    return meth(self, *args, **kwargs)
	  File "/app/splash/qtrender_lua.py", line 2326, in dispatch
	    super(SplashCoroutineRunner, self).dispatch(cmd_id, *args)
	  File "/app/splash/lua_runner.py", line 201, in dispatch
	    self.on_async_command(cmd)
	  File "/app/splash/qtrender_lua.py", line 2322, in on_async_command
	    self.splash.run_async_command(cmd)
	  File "/app/splash/qtrender_lua.py", line 1419, in run_async_command
	    return cmd.kwargs["func"]()
	  File "/app/splash/qtrender_lua.py", line 640, in start
	    run_coro.runner = run_coro()
	  File "/app/splash/qtrender_lua.py", line 1442, in func
	    runner.start(coro, coro_args, return_result, return_error)
	  File "/app/splash/qtrender_lua.py", line 2312, in start
	    super(SplashCoroutineRunner, self).start(coro_func, coro_args)
	  File "/app/splash/lua_runner.py", line 71, in start
	    self.dispatch(self._waiting_for_result_id)
	  File "/app/splash/qtrender.py", line 17, in stop_on_error_wrapper
	    self.return_error(e)
	  File "/app/splash/qtrender_lua.py", line 632, in coro_error
	    info = str(ex.args[0]["error"])
	builtins.KeyError: 'error'
```
