### ISSUE TITLE
Scrapy_splash use chromium ERROR

### ISSUE THREAD

**Issue by toheart** [scrapinghub/splash#964]
Splash version: 3.4 
engine: chromium
Code: 
```python
  SplashRequest(url=url,
                            callback=self.parse,
                            args={
                                'wait': 0.5,
                                'image': 0,
                                'render_all': 1,
                                'engine': 'chromium'
                            },
                            meta={
                                'depth': 0,
                                'download_timeout': self.wait_time,
                                'page_type': conf.PageType.IN_CHAIN
                            }, errback=self.error_failure)
```
Error:
```python
'Traceback (most recent call last):\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks\n    self._runCallbacks()\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator\n    return _cancellableInlineCallbacks(gen)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks\n    _inlineCallbacks(None, g, status)\n--- <exception caught here> ---\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks\n    result = g.send(result)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy/core/downloader/middleware.py", line 53, in process_response\n    spider=spider)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy_splash/middleware.py", line 388, in process_response\n    response = self._change_response_class(request, response)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy_splash/middleware.py", line 409, in _change_response_class\n    response = response.replace(cls=respcls, request=request)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy/http/response/text.py", line 54, in replace\n    return Response.replace(self, *args, **kwargs)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy/http/response/__init__.py", line 81, in replace\n    return cls(*args, **kwargs)\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy_splash/response.py", line 99, in __init__\n    self._load_from_json()\n  File "/root/venv/WebMonitor/lib/python3.7/site-packages/scrapy_splash/response.py", line 145, in _load_from_json\n    error = self.data[\'info\'][\'error\']\nbuiltins.TypeError: string indices must be integers\n'
```
Reason:
![image](https://user-images.githubusercontent.com/15103096/68522711-60a0ae00-02e9-11ea-8ab4-75a57aa78313.png)
  If POST Request have headers, the splash send error back。

**Comment by eherrerosj** [comment]
Same problem here, did you find any way to solve it?

**Comment by davidkong0987** [comment]
`http://0.0.0.0:8050/info?engine=chromium&wait=0.5&images=1&expand=1&timeout=90.0&url=https://www.lightship.capital/portfolio%2F&lua_source=function+main%28splash%2C+args%29%0D%0A++assert%28splash%3Ago%28args.url%29%29%0D%0A++assert%28splash%3Await%280.5%29%29%0D%0A++return+%7B%0D%0A++++html+%3D+splash%3Ahtml%28%29%2C%0D%0A++++png+%3D+splash%3Apng%28%29%2C%0D%0A++++har+%3D+splash%3Ahar%28%29%2C%0D%0A++%7D%0D%0Aend`

does not work

however

`http://0.0.0.0:8050/render.html?engine=chromium&wait=0.5&images=1&expand=1&timeout=90.0&url=https://www.lightship.capital/portfolio%2F&lua_source=function+main%28splash%2C+args%29%0D%0A++assert%28splash%3Ago%28args.url%29%29%0D%0A++assert%28splash%3Await%280.5%29%29%0D%0A++return+%7B%0D%0A++++html+%3D+splash%3Ahtml%28%29%2C%0D%0A++++png+%3D+splash%3Apng%28%29%2C%0D%0A++++har+%3D+splash%3Ahar%28%29%2C%0D%0A++%7D%0D%0Aend`

works

**Comment by dekotale** [comment]
Any solution? still hapenning now with splash 3.5
